<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        // Add temporary BIGINT column
        Schema::table('books', function (Blueprint $table) {
            $table->unsignedBigInteger('date_int')->nullable()->after('employee_id');
        });

        // Backfill from DATE to Unix timestamp (midnight)
        DB::statement("UPDATE books SET date_int = UNIX_TIMESTAMP(date)");

        // Drop existing composite index if exists (name as generated by Laravel)
        // and recreate using the new column
        try {
            DB::statement("ALTER TABLE books DROP INDEX books_employee_id_date_time_slot_index");
        } catch (\Throwable $e) {
            // Ignore if index doesn't exist
        }

        // Drop old date column and rename new column
        DB::statement("ALTER TABLE books DROP COLUMN date");
        DB::statement("ALTER TABLE books CHANGE date_int date BIGINT UNSIGNED NOT NULL");

        // Recreate composite index with the new BIGINT date
        try {
            DB::statement("ALTER TABLE books ADD INDEX books_employee_id_date_time_slot_index (`employee_id`, `date`, `time_slot`)");
        } catch (\Throwable $e) {
            // Ignore if already exists
        }
    }

    public function down(): void
    {
        // Add temporary DATE column
        Schema::table('books', function (Blueprint $table) {
            $table->date('date_dt')->nullable()->after('employee_id');
        });

        // Backfill from Unix timestamp to DATE
        DB::statement("UPDATE books SET date_dt = FROM_UNIXTIME(date)");

        // Drop index on (employee_id, date, time_slot) and recreate after renaming
        try {
            DB::statement("ALTER TABLE books DROP INDEX books_employee_id_date_time_slot_index");
        } catch (\Throwable $e) {
            // Ignore if not exists
        }

        // Drop BIGINT column and rename back
        DB::statement("ALTER TABLE books DROP COLUMN date");
        DB::statement("ALTER TABLE books CHANGE date_dt date DATE NOT NULL");

        // Recreate index
        try {
            DB::statement("ALTER TABLE books ADD INDEX books_employee_id_date_time_slot_index (`employee_id`, `date`, `time_slot`)");
        } catch (\Throwable $e) {
            // Ignore if exists
        }
    }
};
